baseURL = "https://rossn1.github.io/"
publishDir = "docs"
languageCode = "en-gb"
title = "ross."
theme = "PaperMod"
canonifyURLs = true

# Recommended PaperMod params
[params]
  defaultTheme = "auto"        # auto-switches light/dark
  disableThemeToggle = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true

[params.assets]
  disableFingerprinting = true          # disables hashed filenames + SRI

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
